name: data-status

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure pip caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Copy master folder
      run: |-
        rsync -Rr ./ ./master/
    - name: Checkout data branch
      run: |-
        git checkout data
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./master/requirements.txt
    - name: Run forecast
      env:
        AF_URL: ${{ secrets.AF_URL }}
        AF_TOKEN: ${{ secrets.AF_TOKEN }}
      run: |-
        python ./master/option_cron_job.py
    - name: Copy output
      run: |-
        cp -r ./master/output ./
    - name: Delete master folder
      run: |-
        rm -rf ./master
    - name: Add output and push it
      run: |-
        git config --global user.name "zmcx16-bot"
        git reset --soft HEAD~1
        git add ./output/\* && git commit -m "updated output"
        git push -f
