name: OptionValueData

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 4 * * *'
jobs:
  build:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure pip caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Copy master folder
      run: |-
        rsync -Rr ./ ./master/
    - name: Checkout data branch
      run: |-
        git checkout data
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./master/requirements.txt
    - name: Run update option data
      env:
        AF_URL: ${{ secrets.AF_URL }}
        AF_TOKEN: ${{ secrets.AF_TOKEN }}
      run: |-
        python ./master/option_cron_job.py
    - name: Copy output
      run: |-
        cp -r ./master/output ./
    - name: Delete master folder
      run: |-
        rm -rf ./master
    - name: Checkout Norn-StockScreener
      uses: actions/checkout@v2
      with: 
        ref: gh-pages
        repository: zmcx16/Norn-StockScreener
        token: ${{ secrets.ACTIONS_TOKEN }}
        path: ./Norn-StockScreener
        fetch-depth: 0
    - name: Copy options & push Norn-StockScreener
      run: |-
        rm -f ./Norn-StockScreener/norn-data/options/*
        cp -r ./output ./Norn-StockScreener/norn-data/
        cd ./Norn-StockScreener
        mv ./norn-data/output ./norn-data/options
        git config --global user.name "zmcx16-bot"
        git config --global user.email "zmcx16-bot@zmcx16.moe"
        git reset --soft "gh-pages^"
        git add ./norn-data/options/\* && git commit -m "updated options"
        git push -f
