name: TempTest

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure pip caching
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Installed package list
      run: |-
        apt list --installed
    - name: Install Python dependencies
      run: |-
        python -m pip install -r ./requirements-yahoo_finance_cron_job.txt
    - name: Run temp test
      env:
        AF_URL: ${{ secrets.AF_URL }}
        AF_TOKEN: ${{ secrets.AF_TOKEN }}
      run: |-
        python ./test.py
